apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rrle9jaft-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rrle9jaft-go 
  name: rrle9jaft-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rrle9jaft-go 
