apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rrle9jaft-go-gitops
  description: This is GitOps manifest for rrle9jaft-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rrle9jaft-go
    backstage.io/kubernetes-id: rrle9jaft-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rrle9jaft-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rrle9jaft-go
